services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: credit-intel-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - model_data:/data

  scheduler:
    image: credit-intel-scheduler:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["python", "-m", "app.scheduler.run"]
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - model_data:/data

  frontend:
    image: credit-intel-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
  model_data:

